-- PostgreSQL database dump

-- Create table
CREATE TABLE IF NOT EXISTS public.mutual_funds_db (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255),
    ticker VARCHAR(255),
    market_rate DOUBLE PRECISION NOT NULL,
    risk_rate DOUBLE PRECISION NOT NULL
);

-- Insert seed data
INSERT INTO public.mutual_funds_db (id, name, ticker, market_rate, risk_rate) VALUES
(1, 'American Funds Growth Fund of America', 'AGTHX', 0.2843, 0.0335),
(3, 'Vanguard 500 Index Investor Shares', 'VFINX', 0.2484, 0.0427),
(5, 'Dodge & Cox Stock Fund', 'DODGX', 0.1451, 0.0302),
(6, 'T. Rowe Price Blue Chip Growth Fund', 'TRBCX', 0.3563, 0.03),
(7, 'Morgan Stanley Institutional Fund Trust', 'MUAIX', 0.0536, 0.0336),
(8, 'JPMorgan Large Cap Growth R5', 'JLGRX', 0.3405, 0.031),
(9, 'T. Rowe Price Capital Appreciation I', 'TRAIX', 0.1284, 0.0405),
(10, 'JPMorgan Equity Income Fund', 'JUESX', 0.2397, 0.0307),
(11, 'American Funds Growth Fund of America', 'APGAX', 0.2514, 0.0314),
(12, 'Vanguard 500 Index Institutional Select Shares', 'VFFSX', 0.25, 0.0325),
(13, 'BlackRock High Yield Instutitional', 'BHYIX', 0.0863, 0.0235),
(14, 'BlackRock Strategic Income Opportuni Dties Inv A', 'BASIX', 0.053, 0.0403)
ON CONFLICT (id) DO NOTHING;

-- Set sequence to correct value
SELECT setval('public.mutual_funds_db_id_seq', (SELECT MAX(id) FROM public.mutual_funds_db));
