CREATE TABLE mutual_funds_db
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    ticker      VARCHAR(255),
    name        VARCHAR(255),
    risk_rate   DOUBLE PRECISION                        NOT NULL,
    market_rate DOUBLE PRECISION                        NOT NULL,
    CONSTRAINT pk_mutualfundsdb PRIMARY KEY (id)
);