spring.application.name=mutualfunds

# PostgreSQL Database Configuration
spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/mutualfunds}
spring.datasource.username=${DATABASE_USERNAME:postgres}
spring.datasource.password=${DATABASE_PASSWORD:Adgjmptw!23}

# JDBC Driver (optional, Spring Boot auto-detects it)
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate JPA Configuration (for Spring Data JPA)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Server Configuration
server.port=${PORT:8095}